version: '3.8'

services:
  localstack:
    container_name: taller3_localstack
    image: localstack/localstack:3.4.0 
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1

  mongodb:
    container_name: taller3_mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: